pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo Hello, Azure!'
